### ISSUE TITLE
Slight misalignment when using &

### ISSUE THREAD

**Issue by RomeoV** [ludwig-austermann/ouset#1]
Hello, thanks for this package. Unfortunately, when using the `&` option, there seems to be a slight mis-alignment.
Specifically, `typst` seems to insert the `&` in the "center" of the following character, but this package inserts it before.

See this code snippet and the result (on typst 0.11).

![screenshot_2024-05-30T00:03:01UTC](https://github.com/ludwig-austermann/typst-ouset/assets/8644490/33d9942b-bdcc-47ba-b32b-29a3c3c8c37f)

```typst
#import "@preview/ouset:0.1.1": ouset
$
x &= 1 \
  ouset(&, =, "wlog1") 2 \
  ouset(&, =, "wlog2", clip:0) 3 \
  ouset(&, =, "wlog2", clip:1) 4 \
  ouset(=, "wlog5", &) 2 \
  &= 5

$
```

I don't know if there's an easy fix for this, however. Thanks!

**Comment by ludwig-austermann** [comment]
Hmm, I tried the code on various versions of typst. It seems, that ouset worked fine before v0.11.

I will try to identify the problem.

**Comment by ludwig-austermann** [comment]
I noticed, that
```typst
Hello #math.script("World")
```
does not scale in Typst v0.11. This is what I use to do the calculations inside `ouset`. I created an issue at [typst](https://github.com/typst/typst/issues/4303), but have a solution ready, which I will publish soon.

**Comment by RomeoV** [comment]
I can confirm that on Typst v0.10 the alignment looks right, also for more complicated examples.

**Comment by ludwig-austermann** [comment]
The new version v0.2 is now published.

**Comment by RomeoV** [comment]
Can confirm it works!
